version: '3.8'

services:
  app:
    build:
      context: .
    container_name: 'app'
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: 'postgres:15.4-alpine'
    container_name: 'postgres_db'
    environment:
      - POSTGRES_DB=open_weather
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

