create table open_weather.public.locations (
            id integer generated by default as identity,
            latitude float(53),
            longitude float(53),
            name varchar(255),
            userid integer,
            primary key (id)
);
create table open_weather.public.sessions (
             id varchar(255) not null,
             expiresat timestamp(6),
             userid integer,
             primary key (id)
);
create table open_weather.public.users (
             id integer generated by default as identity,
             login varchar(64),
             password varchar(64),
             primary key (id)
);
alter table if exists open_weather.public.users
    add constraint UK_ow0gan20590jrb00upg3va2fn unique (login);
alter table if exists open_weather.public.locations
    add constraint FKatow05gq6bh4cuqqfyh1if4gi
        foreign key (userid)
            references open_weather.public.users;
alter table if exists open_weather.public.sessions
    add constraint FKhhicn3brukxnn876dpg8b6mp1
        foreign key (userid)
            references open_weather.public.users;